### ISSUE TITLE
Add a free license

### ISSUE THREAD

**Issue by pizzamaker** [sstangl/tuja-vortaro#1]
I suggest AGPLv3+

**Comment by sstangl** [comment]
Ankaŭ mi preferus AGPLv3+. Sed ne certas ĉu eblas. La vortaro nune uzas dataon de ESPDIC kaj de ReVo. ReVo estas eldonita nur sub la GPLv2. Tial mi eldonu ankaŭ tiun projekton sub GPLv2. Mi ne baraktus, ĉar tamen ĝi liberas.

Eble en la estonteco ni povus trovi alian fundon por la vortoj, por ke ni povos ŝanĝi la licencon.

**Comment by sstangl** [comment]
Ni devas montri en la retpaĝo, ke la programo liberas.
