### ISSUE TITLE
De kie ĉu vi obtenas la semantikajn originojn de la vortoj?

### ISSUE THREAD

**Issue by capiscuas** [sstangl/tuja-vortaro#11]
De kie ĉu vi obtenas la semantikajn originojn de la vortoj?
Mi ŝatus scii por kunlabori per novaj semantikaĵoj en tiu bazdutumo.

Dankon.

**Comment by sstangl** [comment]
La fonto de la etimologioj estas https://archive.org/details/EsperantoEtymologicalDictionary. En tiu-ĉi proĵekto ekzistas skripto, kiu povas konverti tiun dokumenton al JS-a: https://github.com/sstangl/tuja-vortaro/tree/master/etymology

Si vi volus pligrandigi la liston de etimologioj en ĉi-tiu vortaro, bonvolu verki en la dosiero https://github.com/sstangl/tuja-vortaro/blob/master/etymology/etymology.txt, ĉar la archive.org-a proĵekto nelonge ekzistas (ŝajne).
