### ISSUE TITLE
Ligila parametro por agordi Chromium-serĉilon

### ISSUE THREAD

**Issue by capiscuas** [sstangl/tuja-vortaro#12]
Saluton, 
mi kutime uzas Chromium-serĉilojn por plirapidigi la serĉon de esperanta vortoj, mi ŝatus aldoni vian retpaĝon www.tujavortaro.net sed mi ne trovas kiel tuj serĉi ligile, ekz:
www.tujavortaro.net/vorto?ekzemplo
do tiel mi povas krei mia novan serĉilo en Chromium kiel www.tujavortaro.net/vorto?%s

Dankegon

**Comment by sstangl** [comment]
Bonega ideo! Ĝi nun funkcionas: http://www.tujavortaro.net/?vorto=serĉo

**Comment by capiscuas** [comment]
Vi estas mirinda kaj rapidega programisto :-). Dankegon.
