### ISSUE TITLE
Feature request: Allow query via URL

### ISSUE THREAD

**Issue by dimitrior** [sstangl/tuja-vortaro#19]
Hi, 

Firstly, congrats to all devs/contributors for a truly excellent tool. 

Secondly - a "feature request" (apologies, I am not a web dev). I would like to ask if it would be possible to allow querying via URL parameters (like this: http://www.tujavortaro.net/{myquery}) - if it is not already possible. This would be useful for integrating TV into e.g. http://readlang.com/settings

Thanks!
Dimitri

**Comment by sstangl** [comment]
The following pattern allows for this:

http://www.tujavortaro.net/?vorto=hello

I don't know if it's really useful for external API-like use, since it still loads the full dictionary and searches via Javascript.

**Comment by dimitrior** [comment]
Bonege, dankon!
